// Secondary market listings — prices in USDT per token, volumes in token count.
// All trades execute via SecondaryMarket.sol on Arbitrum Sepolia.
// listingId = on-chain listing index in SecondaryMarket.listings mapping.
// CEST entry is governance token (Uniswap listing Q2 2026, not yet live on any DEX).

export const CEST_LISTING = {
  listingId:      0,
  ticker:         'CEST',
  name:           'ChainEstate Token',
  location:       'Governance · Arbitrum Sepolia',
  lastPrice:      0.04,
  change24h:      8.2,
  changePositive: true,
  volume24h:      4_820_000,   // CEST traded
  high24h:        0.042,
  low24h:         0.037,
  ask:            0.041,
  bid:            0.039,
  marketCap:      40_000_000,  // 1B × $0.04
  yield:          0,           // governance token, no yield
  isDex:          true,        // trades on DEX, not SecondaryMarket
}

export const MARKET_LISTINGS = [
  {
    listingId:     1,
    ticker:        'PEARL-DXB-001',
    name:          'Pearl Residences',
    location:      'Dubai, UAE',
    lastPrice:     1.02,
    change24h:     2.1,
    changePositive: true,
    volume24h:     14_820,
    high24h:       1.03,
    low24h:        0.99,
    ask:           1.025,
    bid:           1.015,
    marketCap:     510_000,
    yield:         6.8,
  },
  {
    listingId:     2,
    ticker:        'SHIBUYA-TYO-001',
    name:          'Shibuya Terrace',
    location:      'Tokyo, Japan',
    lastPrice:     0.98,
    change24h:     -0.5,
    changePositive: false,
    volume24h:     8_340,
    high24h:       1.00,
    low24h:        0.97,
    ask:           0.985,
    bid:           0.975,
    marketCap:     372_400,
    yield:         5.9,
  },
  {
    listingId:     3,
    ticker:        'MARINA-SGP-001',
    name:          'Marina Heights',
    location:      'Singapore',
    lastPrice:     1.05,
    change24h:     5.3,
    changePositive: true,
    volume24h:     22_100,
    high24h:       1.06,
    low24h:        1.00,
    ask:           1.055,
    bid:           1.045,
    marketCap:     651_000,
    yield:         7.2,
  },
  {
    listingId:     4,
    ticker:        'CANARY-LON-001',
    name:          'Canary Wharf Executive',
    location:      'London, UK',
    lastPrice:     0.99,
    change24h:     -0.1,
    changePositive: false,
    volume24h:     5_670,
    high24h:       1.01,
    low24h:        0.98,
    ask:           0.995,
    bid:           0.985,
    marketCap:     841_500,
    yield:         5.4,
  },
  {
    listingId:     5,
    ticker:        'AZURE-BCN-001',
    name:          'Azure Barcelona Suite',
    location:      'Barcelona, Spain',
    lastPrice:     1.03,
    change24h:     3.0,
    changePositive: true,
    volume24h:     9_950,
    high24h:       1.04,
    low24h:        0.99,
    ask:           1.035,
    bid:           1.025,
    marketCap:     298_700,
    yield:         8.1,
  },
]
