const CONTRACTS = [
  {
    name: 'PropertyToken.sol',
    badge: 'ERC-7984',
    badgeColor: 'var(--nox-green)',
    address: '0x853D51fBD5E288BF189FE0126d59f855c821a641',
    addressLabel: 'PEARL-DXB-001 (example)',
    desc: 'One instance per property, deployed via CREATE2 from PropertyRegistry. The core confidential token — balances stored as euint256, encrypted by Intel TDX TEE. No observer can read holdings.',
    inherits: ['ERC7984 (iExec Nox)', 'Ownable', 'Pausable', 'ReentrancyGuard'],
    functions: [
      { sig: 'purchaseTokens(bytes32 handle, bytes handleProof, uint256 clearAmount)', access: 'public', desc: 'Pay USDT, receive encrypted tokens. handle + handleProof generated by @iexec-nox/handle SDK.' },
      { sig: 'grantOperator(address operator, uint256 expiry)', access: 'holder', desc: 'Delegate transfer rights to SecondaryMarket for listings. Expiry in unix timestamp.' },
      { sig: 'pricePerToken() → uint256', access: 'view', desc: 'Token price in USDT 6 decimals. All 5 deployed = 1_000_000 ($1.00).' },
      { sig: 'propertyId() → uint256', access: 'view', desc: 'ID assigned by PropertyRegistry (1–5 for current properties).' },
    ],
    notes: [
      'Transfers never revert on insufficient balance (ERC-7984 spec — prevents balance inference via gas)',
      'Events do not emit token amounts — privacy by design',
      'Salt for CREATE2 = bytes32(propertyId) → deterministic addresses',
    ],
  },
  {
    name: 'PropertyRegistry.sol',
    badge: 'Factory',
    badgeColor: 'var(--gold-primary)',
    address: '0xCdBCA38E4C86bdC74Cd49D93cE2B88D3ecC00d5e',
    addressLabel: 'Registry (all networks)',
    desc: 'Central registry and CREATE2 factory. Admin lists properties, which deploys a new PropertyToken. Tracks all holders per property for RentDistributor. Currently 5 active properties.',
    inherits: ['Ownable', 'Pausable', 'ReentrancyGuard'],
    functions: [
      { sig: 'listProperty(string name, string location, string ipfsDocHash, uint256 totalSupply, uint256 pricePerToken, uint256 monthlyRent) → (uint256 propertyId, address tokenContract)', access: 'onlyOwner', desc: 'Deploys PropertyToken via CREATE2, registers property. pricePerToken in USDT 6 decimals.' },
      { sig: 'registerHolder(uint256 propertyId, address holder)', access: 'approved', desc: 'Called by PropertyToken on purchase and by approved markets. Prevents duplicate entries.' },
      { sig: 'setApprovedMarket(address market, bool approved)', access: 'onlyOwner', desc: 'Whitelist SecondaryMarket to register buyers as holders post-trade.' },
      { sig: 'getPropertyHolders(uint256 propertyId) → address[]', access: 'view', desc: 'Returns all registered holder addresses. Used by RentDistributor.' },
      { sig: 'properties(uint256) → Property', access: 'view', desc: 'Returns full property struct: id, name, location, supply, price, rent, status, tokenContract.' },
      { sig: 'propertyCount() → uint256', access: 'view', desc: 'Total properties listed. Currently 5.' },
    ],
    notes: [
      'owner() = 0x834De729cb9dF77451DBc6bf7FD05F475B011Ac7 (treasury/deployer)',
      'paused() = false (all contracts operational)',
    ],
  },
  {
    name: 'SecondaryMarket.sol',
    badge: 'P2P Marketplace',
    badgeColor: 'var(--gold-primary)',
    address: '0x77836405DC14Ca1Ef0304041ec8D3B4166424cfa',
    addressLabel: 'Secondary Market',
    desc: 'Fixed-price P2P listing marketplace for property token trading. Sellers post a listing at a fixed price; buyers execute against it. Token amounts moved via confidentialTransferFrom (encrypted). CEST stakers get fee discounts.',
    inherits: ['ReentrancyGuard', 'Pausable'],
    functions: [
      { sig: 'createListing(address tokenContract, uint256 propertyId, uint256 tokenAmount, uint256 pricePerToken) → uint256 listingId', access: 'public', desc: 'Requires grantOperator first. pricePerToken in USDT 6 decimals (e.g. $1.025 = 1_025_000). Returns listingId.' },
      { sig: 'executeBuy(uint256 listingId)', access: 'public', desc: 'Buyer must approve USDT first. Triggers confidentialTransferFrom (encrypted). Deducts 0.5% fee (reduced by CEST tier).' },
      { sig: 'cancelListing(uint256 listingId)', access: 'seller', desc: 'Seller can cancel an active listing at any time.' },
      { sig: 'listings(uint256) → Listing', access: 'view', desc: 'Returns: listingId, seller, tokenContract, propertyId, tokenAmount, pricePerToken, listedAt, active.' },
    ],
    notes: [
      'Fee: 0.5% base, reduced by CEST staking tier (0% for PLATINUM)',
      'Seller must call propertyToken.grantOperator(secondaryMarket, expiry) before listing',
      'Buyer must call usdt.approve(secondaryMarket, totalCost) before executeBuy',
    ],
  },
  {
    name: 'RentDistributor.sol',
    badge: 'Income',
    badgeColor: 'var(--nox-green)',
    address: '0x80E0e5f6488FA2726c042a204344281974f72609',
    addressLabel: 'Rent Distributor',
    desc: 'Receives monthly USDT from the property operator and distributes 90% to all registered holders. Platform takes 5%, maintenance reserve 5%. Equal-share model (not pro-rata) because ERC-7984 balances cannot be read on-chain.',
    inherits: ['ReentrancyGuard', 'Pausable', 'Ownable'],
    functions: [
      { sig: 'depositRent(uint256 propertyId, uint256 amount)', access: 'onlyOwner', desc: 'Deposit USDT rent for a property. Accumulates in pendingRent[propertyId].' },
      { sig: 'distributeRent(uint256 propertyId)', access: 'onlyOwner', desc: 'Distribute accumulated pendingRent — splits: 5% platform + 5% maintenance + 90% equally to all holders.' },
      { sig: 'getDistributionHistory(uint256 propertyId) → RentDistribution[]', access: 'view', desc: 'Returns past distributions for a property.' },
      { sig: 'getPendingRent(uint256 propertyId) → uint256', access: 'view', desc: 'Returns accumulated undistributed rent for a property.' },
    ],
    notes: [
      'Equal share per holder — not pro-rata by token balance',
      'Pro-rata distribution planned for Phase 2 using iExec Nox compute over encrypted balances',
      'All distribution totals are on-chain auditable; per-investor amounts are private',
    ],
  },
  {
    name: 'CESTToken.sol',
    badge: 'ERC20Votes + Nox',
    badgeColor: 'var(--gold-primary)',
    address: '0xC6c08db835636Cf40530dDf90Bf3Bb15bc78190D',
    addressLabel: 'CEST Token',
    desc: 'Utility and future-governance token. 1 Billion total supply. Staking unlocks: (1) SecondaryMarket fee discounts (0.5% → 0% at PLATINUM), (2) TierNFT badge eligibility (determines mint tier). Now includes iExec Nox integration: after staking, holders can call encryptMyStake() to store their staked amount as an encrypted euint256 handle via Nox.fromExternal() — adding a confidential layer on top of the on-chain stake record. Price: $0.04 → $40M market cap.',
    inherits: ['ERC20 (OZ)', 'ERC20Votes (OZ)', 'ERC20Permit (OZ)', 'Ownable (OZ)', 'Nox SDK (iExec)'],
    functions: [
      { sig: 'stake(uint256 amount, uint256 lockDays)', access: 'public', desc: 'Time-lock CEST for tier benefits. Min 30 days, max 365 days. Adds to existing staked amount. Tier automatically recalculates.' },
      { sig: 'unstake(uint256 amount)', access: 'holder', desc: 'Withdraw a specific staked CEST amount after lock period expires. Tier recalculates automatically.' },
      { sig: 'encryptMyStake(externalEuint256 handle, bytes handleProof)', access: 'holder', desc: 'iExec Nox: store your staked amount as encrypted euint256. Call after stake(). Uses Nox.fromExternal(handle, handleProof) — same TEE-verified pattern as PropertyToken. Only you can decrypt your stake amount off-chain via Nox JS SDK.' },
      { sig: 'encryptedStake(address holder) → euint256', access: 'view', desc: 'Returns the Nox-encrypted stake handle. Only readable (decryptable) by the holder via Nox.allow().' },
      { sig: 'getTier(address account) → StakingTier', access: 'view', desc: 'Returns NONE/BRONZE/SILVER/GOLD/PLATINUM based on staked balance. Read by TierNFT.getTier() for badge eligibility.' },
      { sig: 'getFeeDiscount(address account) → uint256', access: 'view', desc: 'Returns discount in BPS (0–10000). PLATINUM = 10000 (100% free). Used by SecondaryMarket.executeBuy().' },
    ],
    notes: [
      'ERC20Votes = delegation only (future DAO) — ConfidentialGovernance uses PropertyToken holder status, not CEST',
      'TierNFT reads CESTToken.getTier() to determine which badge tier a wallet qualifies for',
      'Faucet drips 2,400 CEST (~$96) per address per 24h on testnet',
      'Total supply: 1,000,000,000 · Airdrop pool: 250,000,000 (25%)',
    ],
  },
  {
    name: 'ConfidentialGovernance.sol',
    badge: 'Governance',
    badgeColor: 'var(--nox-green)',
    address: '0x32AC35493ff1E4a550C36AB6BfD2f29a2b021a14',
    addressLabel: 'Confidential Governance',
    desc: 'Property-level governance gated by PropertyToken (ERC-7984) holder status — NOT by CEST token. Each verified holder gets exactly 1 vote regardless of their encrypted token balance, preventing whale dominance while preserving full privacy. Holder status checked via registry.isHolder().',
    inherits: ['Ownable'],
    functions: [
      { sig: 'createProposal(uint256 propertyId, ProposalType proposalType, string description) → uint256 proposalId', access: 'onlyHolder', desc: 'Create a governance proposal for a property. ProposalType: RentAdjustment | Maintenance | PropertyStatus | Other.' },
      { sig: 'castVote(uint256 proposalId, VoteOption option)', access: 'holder', desc: '1 address = 1 vote. VoteOption: For | Against | Abstain. Balance-blind — no whale advantage visible on-chain.' },
      { sig: 'finalizeProposal(uint256 proposalId)', access: 'public', desc: 'Finalize a proposal after voting deadline. Checks quorum and majority. Any address can call.' },
      { sig: 'getProposal(uint256 proposalId) → Proposal', access: 'view', desc: 'Returns full proposal struct including vote counts and execution status.' },
      { sig: 'getProposalsByProperty(uint256 propertyId) → Proposal[]', access: 'view', desc: 'Returns all proposals for a property.' },
    ],
    notes: [
      'Access control: registry.isHolder(propertyId, msg.sender) — no balance exposed',
      '1 address = 1 vote (balance-blind for privacy)',
      'Proposals: rent adjustments, maintenance, property status changes',
    ],
  },
  {
    name: 'TierNFT.sol',
    badge: 'Soulbound NFT',
    badgeColor: 'var(--nox-green)',
    address: '0xda3072dd0B56e81B0361c760eCF512F1B85FFFfc',
    addressLabel: 'TierNFT — live on Arbitrum Sepolia',
    desc: 'Soulbound (non-transferable) ERC-721 tier badge. Minted by staking CEST via CESTToken.stake() and paying a CEST burn cost to the treasury (fee-discount reserve pool). Four tiers: Bronze / Silver / Gold / Platinum. Gold and Platinum additionally require the caller to hold a Nox ERC-7984 PropertyToken — proved via PropertyRegistry.isHolder(). On-chain testnet interaction points are stored as encrypted euint256 using Nox.fromExternal() + Nox.add() — the same TEE-verified pattern as PropertyToken.purchaseTokens(). No observer can read your point balance.',
    inherits: ['ERC721 (OZ)', 'Ownable (OZ)', 'ReentrancyGuard (OZ)', 'Nox SDK (iExec)'],
    functions: [
      { sig: 'mint()', access: 'public', desc: 'Mint your tier badge. Requires: (1) CESTToken.stake(amount, days) to reach a tier, (2) CEST.approve(TierNFT, mintCost). CEST cost is sent to treasury. Gold/Platinum also require PropertyRegistry.isHolder() (Nox gate).' },
      { sig: 'upgrade()', access: 'holder', desc: 'Upgrade existing badge to a higher tier by paying only the cost delta. Example: Bronze→Gold = 8,000−500 = 7,500 CEST. Requires CESTToken.getTier() to have increased.' },
      { sig: 'recordPoints(address holder, externalEuint256 handle, bytes handleProof)', access: 'onlyOwner', desc: 'Record encrypted testnet interaction points. Uses Nox.fromExternal(handle, handleProof) — same pattern as PropertyToken. Points are accumulated as euint256: never readable on-chain. Only holder can decrypt via Nox JS SDK.' },
      { sig: 'getTier(address holder) → Tier', access: 'view', desc: 'Returns live eligible tier based on CESTToken.getTier() (staked amount). None/Bronze/Silver/Gold/Platinum.' },
      { sig: 'airdropMultiplierBps(address holder) → uint16', access: 'view', desc: 'Returns airdrop multiplier in BPS (100=1×, 110=1.1×, 125=1.25×, 150=1.5×, 200=2×) based on minted badge tier.' },
      { sig: 'feeDiscount(address holder) → uint8', access: 'view', desc: 'Returns fee discount percentage (0/5/10/15/20) based on minted badge tier.' },
      { sig: 'encryptedPoints(address holder) → euint256', access: 'view', desc: 'Returns the Nox-encrypted points handle. Requires Nox.allow() access — only holder can decrypt off-chain.' },
      { sig: 'hasBadge(address holder) → bool', access: 'view', desc: 'Returns true if the wallet has minted a badge.' },
      { sig: 'badgeTier(address holder) → Tier', access: 'view', desc: 'Returns the tier of the minted badge (may differ from live getTier if balance dropped).' },
    ],
    notes: [
      'Soulbound: _update() reverts on wallet-to-wallet transfer (ERC-721 override)',
      'Mint costs burned to treasury: Bronze 500 · Silver 2K · Gold 8K · Platinum 25K CEST',
      'upgrade() costs delta only: e.g. Silver→Platinum = 25,000−2,000 = 23,000 CEST',
      'Point amounts omitted from PointsRecorded event — confidentiality by design',
      'Gold/Platinum require PropertyRegistry.isHolder() — must have purchased via Nox TEE first',
    ],
  },
]

export default function ContractsPage() {
  return (
    <div>
      <p className="text-xs font-body uppercase tracking-[0.28em] mb-3" style={{ color: 'var(--nox-green)' }}>
        Docs / Smart Contracts
      </p>
      <h1 className="font-display text-4xl mb-4" style={{ color: 'var(--text-primary)' }}>
        Smart Contracts
      </h1>
      <p className="text-base font-body leading-relaxed mb-4 max-w-2xl" style={{ color: 'var(--text-secondary)' }}>
        All contracts are deployed and verified on Arbitrum Sepolia (chainId 421614).
        Source in <code className="font-data text-sm" style={{ color: 'var(--gold-primary)' }}>contracts/</code>.
        ABIs in <code className="font-data text-sm" style={{ color: 'var(--gold-primary)' }}>artifacts/</code>.
        Frontend ABIs in <code className="font-data text-sm" style={{ color: 'var(--gold-primary)' }}>app/lib/contracts.ts</code>.
      </p>

      {/* Architecture diagram */}
      <div className="rounded-xl p-5 mb-10 font-data text-xs leading-relaxed" style={{ background: 'var(--bg-surface)', border: '1px solid var(--border-visible)', color: 'var(--text-secondary)' }}>
        <p className="mb-1" style={{ color: 'var(--text-ghost)' }}>// Architecture</p>
        <pre className="overflow-x-auto">{`Wallet
  │
  ├─ @iexec-nox/handle → { handle, handleProof }   ← Intel TDX TEE
  │
  ├─ usdt.approve(PropertyToken, amount)
  └─ PropertyToken.purchaseTokens(handle, proof, amount)
         │  Nox.fromExternal(handle, proof) → euint256 (encrypted balance)
         │  Nox.allowThis + Nox.allow(amount, wallet)
         │
         ├─ PropertyRegistry.registerHolder(propertyId, wallet)
         │        │
         │        ├─ RentDistributor.distributeRent() → USDT per holder (equal share)
         │        │
         │        └─ TierNFT.mint() ← Gold/Platinum require isHolder() gate
         │
         ├─ SecondaryMarket
         │        │  grantOperator → createListing(tokenContract, id, amount, price)
         │        │  usdt.approve(SecondaryMarket) → executeBuy(listingId)
         │        │  confidentialTransferFrom (encrypted) via ERC-7984
         │        │
         │        └─ CESTToken.stake() → getTier() → fee discount (0.5% → 0%)
         │
         ├─ ConfidentialGovernance
         │        │  registry.isHolder() → onlyHolder gate
         │        └─ createProposal / castVote / finalizeProposal
         │
         └─ TierNFT (Soulbound)
                  │  CESTToken.getTier() → badge tier eligibility
                  │  CEST burned → treasury (fee-discount reserve)
                  │  recordPoints(wallet, handle, proof) → euint256 encrypted points
                  └─ airdropMultiplierBps / feeDiscount`}</pre>
      </div>

      {/* Nox Integration Summary */}
      <h2 className="font-display text-xl mb-4" style={{ color: 'var(--text-primary)' }}>
        iExec Nox Integration — All Contracts
      </h2>
      <div className="rounded-xl overflow-hidden mb-10" style={{ border: '1px solid rgba(0,229,160,0.25)' }}>
        {[
          ['Contract', 'Nox Imports', 'What It Does'],
          [
            'PropertyToken.sol',
            'ERC7984, Nox, euint256, externalEuint256',
            'purchaseTokens() — Nox.fromExternal(handle, proof) → euint256 encrypted balance. confidentialTransfer / confidentialTransferFrom for private moves.',
          ],
          [
            'TierNFT.sol',
            'Nox, euint256, externalEuint256',
            'recordPoints() — Nox.fromExternal(handle, proof) + Nox.add() accumulates encrypted points per wallet. Only holder can decrypt via Nox JS SDK. PropertyRegistry.isHolder() gates Gold/Platinum mint.',
          ],
          [
            'CESTToken.sol',
            'Nox, euint256, externalEuint256',
            'encryptMyStake() — after staking CEST, holder encrypts their stake amount as euint256. Nox.fromExternal(handle, proof). Confidential layer on top of public stake record.',
          ],
          [
            'SecondaryMarket.sol',
            'via ERC7984 interface',
            'executeBuy() calls PropertyToken.operatorTransfer() which uses confidentialTransferFrom — encrypted amount moves without revealing quantity on-chain.',
          ],
          [
            'RentDistributor.sol',
            'via PropertyToken interface',
            'distributeRent() calls operatorTransfer for each holder — USDT amounts auditable on-chain, but per-investor token positions remain encrypted.',
          ],
          [
            'ConfidentialGovernance.sol',
            'via PropertyRegistry',
            'onlyHolder modifier uses registry.isHolder() — membership gated by ERC-7984 Nox token holding. 1-address-1-vote preserves balance privacy.',
          ],
        ].map(([contract, imports, what], i) => (
          <div
            key={contract}
            className="grid px-5 py-3.5 text-xs font-body"
            style={{
              gridTemplateColumns: i === 0 ? '180px 220px 1fr' : '180px 220px 1fr',
              background: i === 0 ? 'rgba(0,229,160,0.07)' : i % 2 === 0 ? 'rgba(255,255,255,0.02)' : 'transparent',
              borderBottom: i < 6 ? '1px solid var(--border-subtle)' : 'none',
              alignItems: 'start',
              gap: '12px',
            }}
          >
            <span className="font-data" style={{ color: i === 0 ? 'var(--text-ghost)' : 'var(--nox-green)' }}>{contract}</span>
            <span className="font-data text-[10px] leading-relaxed" style={{ color: i === 0 ? 'var(--text-ghost)' : 'var(--gold-primary)' }}>{imports}</span>
            <span style={{ color: i === 0 ? 'var(--text-ghost)' : 'var(--text-secondary)' }}>{what}</span>
          </div>
        ))}
      </div>

      {/* iApp Live Test Evidence */}
      <div className="rounded-xl overflow-hidden mb-10" style={{ border: '1px solid rgba(0,229,160,0.3)' }}>
        <div className="flex flex-wrap items-center justify-between gap-3 px-6 py-4" style={{ background: 'rgba(0,229,160,0.07)', borderBottom: '1px solid rgba(0,229,160,0.2)' }}>
          <div className="flex items-center gap-3">
            <span className="h-2 w-2 rounded-full" style={{ background: 'var(--nox-green)', boxShadow: '0 0 8px rgba(0,229,160,0.6)' }} />
            <h2 className="font-display text-base" style={{ color: 'var(--text-primary)' }}>iApp Live Test Evidence</h2>
            <span className="px-2 py-0.5 rounded text-[9px] font-body uppercase tracking-wider" style={{ background: 'rgba(0,229,160,0.12)', color: 'var(--nox-green)', border: '1px solid rgba(0,229,160,0.3)' }}>
              Verified on iExec
            </span>
          </div>
          <div className="flex items-center gap-3">
            <a
              href="https://explorer.iex.ec/arbitrum-sepolia-testnet/account?accountTab=Wallet+Activity&walletActivityAddressTab=REQUESTS"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[10px] font-data transition-opacity hover:opacity-70"
              style={{ color: 'var(--text-ghost)' }}
            >
              Arbitrum Sepolia ↗
            </a>
            <span style={{ color: 'var(--border-visible)' }}>·</span>
            <a
              href="https://explorer.iex.ec/bellecour/address/0x834De729cb9dF77451DBc6bf7FD05F475B011Ac7"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[10px] font-data transition-opacity hover:opacity-70"
              style={{ color: 'var(--text-ghost)' }}
            >
              Bellecour ↗
            </a>
          </div>
        </div>

        <div className="px-6 py-5 space-y-6">
          <p className="text-sm font-body leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
            The iExec Nox iApp was live-tested on <strong style={{ color: 'var(--text-primary)' }}>April 30, 2026</strong> against the Arbitrum Sepolia PropertyToken contracts.
            All 5 latest tasks completed successfully — 100% success rate on the latest test run. All deals used the same Intel TDX enclave, confirming the full TEE encryption pipeline is operational end-to-end.
          </p>

          {/* Stats row */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {[
              { label: 'Latest Tasks', value: '5 / 5', color: 'var(--nox-green)', sub: '100% — latest run' },
              { label: 'Total Deals', value: '8+', color: 'var(--nox-green)', sub: 'all at 0.1 RLC' },
              { label: 'Deal Price', value: '0.1 RLC', color: 'var(--gold-primary)' },
              { label: 'Test Date', value: '30 Apr 2026', color: 'var(--text-secondary)' },
            ].map(s => (
              <div key={s.label} className="rounded-xl p-3 text-center" style={{ background: 'rgba(0,0,0,0.3)', border: '1px solid var(--border-subtle)' }}>
                <p className="text-[10px] font-body uppercase tracking-widest mb-1" style={{ color: 'var(--text-ghost)' }}>{s.label}</p>
                <p className="font-data text-lg" style={{ color: s.color }}>{s.value}</p>
                {s.sub && <p className="text-[9px] font-body mt-0.5" style={{ color: 'var(--text-ghost)' }}>{s.sub}</p>}
              </div>
            ))}
          </div>

          {/* iApp + Workerpool */}
          <div className="grid gap-3 sm:grid-cols-2">
            <div className="rounded-xl p-4" style={{ background: 'rgba(0,229,160,0.04)', border: '1px solid rgba(0,229,160,0.15)' }}>
              <p className="text-[10px] font-body uppercase tracking-widest mb-2" style={{ color: 'var(--text-ghost)' }}>iApp (TEE Enclave)</p>
              <a
                href="https://explorer.iex.ec/bellecour/app/0xB11bC7288eE239F6536829E410d22Eb514C5E282"
                target="_blank"
                rel="noopener noreferrer"
                className="font-data text-xs hover:opacity-70 transition-opacity"
                style={{ color: 'var(--nox-green)' }}
              >
                0xB11bC7288eE239F6536829E410d22Eb514C5E282 ↗
              </a>
              <p className="text-[10px] font-body mt-2" style={{ color: 'var(--text-ghost)' }}>jancok075/iexec:0.0.1-tdx-1f1d5e8f915a</p>
              <p className="text-[10px] font-body mt-0.5" style={{ color: 'var(--text-ghost)' }}>Tag: tee,tdx — Intel TDX hardware enclave</p>
            </div>
            <div className="rounded-xl p-4" style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid var(--border-subtle)' }}>
              <p className="text-[10px] font-body uppercase tracking-widest mb-2" style={{ color: 'var(--text-ghost)' }}>Requester Wallet</p>
              <a
                href="https://explorer.iex.ec/arbitrum-sepolia-testnet/account?accountTab=Wallet+Activity&walletActivityAddressTab=REQUESTS"
                target="_blank"
                rel="noopener noreferrer"
                className="font-data text-xs hover:opacity-70 transition-opacity"
                style={{ color: 'var(--gold-primary)' }}
              >
                0x834De729cb9dF77451DBc6bf7FD05F475B011Ac7 ↗
              </a>
              <p className="text-[10px] font-body mt-2" style={{ color: 'var(--text-ghost)' }}>Workerpool</p>
              <p className="font-data text-[10px] mt-0.5" style={{ color: 'var(--text-ghost)' }}>0x2956f0...3123f</p>
            </div>
          </div>

          {/* Task log */}
          <div>
            <p className="text-[10px] font-body uppercase tracking-widest mb-3" style={{ color: 'var(--text-ghost)' }}>Latest Requested Tasks — April 30, 2026</p>
            <div className="rounded-xl overflow-hidden" style={{ border: '1px solid var(--border-subtle)' }}>
              <div className="grid grid-cols-[1fr_120px_1fr] px-4 py-2 text-[10px] font-body uppercase tracking-widest" style={{ background: 'var(--bg-elevated)', color: 'var(--text-ghost)', borderBottom: '1px solid var(--border-subtle)' }}>
                <span>Task ID</span><span>Status</span><span>Deadline</span>
              </div>
              {[
                { id: '0x7c10bc…de3a1', status: 'COMPLETED', time: '04/30/2026 01:33 PM', ok: true },
                { id: '0xca537d…1fcc3', status: 'COMPLETED', time: '04/30/2026 01:26 PM', ok: true },
                { id: '0xee7f34…80365', status: 'COMPLETED', time: '04/30/2026 01:25 PM', ok: true },
                { id: '0x423c62…8a4d9', status: 'COMPLETED', time: '04/30/2026 11:26 AM', ok: true },
                { id: '0x6091cf…5df0d', status: 'COMPLETED', time: '04/30/2026 09:42 AM', ok: true },
              ].map((t, i) => (
                <div
                  key={t.id}
                  className="grid grid-cols-[1fr_120px_1fr] px-4 py-3 text-xs font-body items-center"
                  style={{ borderTop: i > 0 ? '1px solid var(--border-subtle)' : 'none', background: i % 2 === 0 ? 'transparent' : 'rgba(255,255,255,0.01)' }}
                >
                  <code className="font-data text-[11px]" style={{ color: 'var(--text-secondary)' }}>{t.id}</code>
                  <span
                    className="inline-flex items-center gap-1.5 text-[10px] uppercase tracking-widest"
                    style={{ color: 'var(--nox-green)' }}
                  >
                    <span className="h-1.5 w-1.5 rounded-full shrink-0" style={{ background: 'var(--nox-green)' }} />
                    {t.status}
                  </span>
                  <span className="font-data text-[10px]" style={{ color: 'var(--text-ghost)' }}>{t.time}</span>
                </div>
              ))}
            </div>
            <p className="mt-2 text-[10px] font-body" style={{ color: 'var(--text-ghost)' }}>
              Showing page 1 of 3 — all 5 latest tasks COMPLETED. Full history at iExec Explorer ↗
            </p>
          </div>

          {/* Deal log */}
          <div>
            <p className="text-[10px] font-body uppercase tracking-widest mb-3" style={{ color: 'var(--text-ghost)' }}>Latest Requested Deals — iApp 0xb11bc7…5e282</p>
            <div className="rounded-xl overflow-hidden" style={{ border: '1px solid var(--border-subtle)' }}>
              <div className="grid grid-cols-[1fr_80px_60px_60px] px-4 py-2 text-[10px] font-body uppercase tracking-widest" style={{ background: 'var(--bg-elevated)', color: 'var(--text-ghost)', borderBottom: '1px solid var(--border-subtle)' }}>
                <span>Deal ID</span><span>Time</span><span>Success</span><span>Price</span>
              </div>
              {[
                { id: '0xe8990c…76b95', time: '1h ago', success: '100%' },
                { id: '0x3d6a21…2d00b', time: '1h ago', success: '100%' },
                { id: '0xaa4fd6…3c3b7', time: '1h ago', success: '100%' },
                { id: '0x8e424d…9119c', time: '3h ago', success: '100%' },
                { id: '0x31da2e…17358', time: '5h ago', success: '100%' },
              ].map((d, i) => (
                <div
                  key={d.id}
                  className="grid grid-cols-[1fr_80px_60px_60px] px-4 py-3 text-xs font-body items-center"
                  style={{ borderTop: i > 0 ? '1px solid var(--border-subtle)' : 'none', background: i % 2 === 0 ? 'transparent' : 'rgba(255,255,255,0.01)' }}
                >
                  <code className="font-data text-[11px]" style={{ color: 'var(--text-secondary)' }}>{d.id}</code>
                  <span className="font-data text-[10px]" style={{ color: 'var(--text-ghost)' }}>{d.time}</span>
                  <span className="font-data text-[11px]" style={{ color: 'var(--nox-green)' }}>{d.success}</span>
                  <span className="font-data text-[10px]" style={{ color: 'var(--gold-primary)' }}>0.1 RLC</span>
                </div>
              ))}
            </div>
            <p className="mt-2 text-[10px] font-body" style={{ color: 'var(--text-ghost)' }}>
              Showing page 1 of 3 — all latest deals at 100% success. Workerpool: 0x2956f0…3123f · No dataset.
            </p>
          </div>
        </div>
      </div>

      {/* IPFS Document Registry */}
      <div className="rounded-xl overflow-hidden mb-10" style={{ border: '1px solid rgba(212,175,55,0.3)' }}>
        <div className="flex flex-wrap items-center justify-between gap-3 px-6 py-4" style={{ background: 'rgba(212,175,55,0.06)', borderBottom: '1px solid rgba(212,175,55,0.2)' }}>
          <div className="flex items-center gap-3">
            <span className="h-2 w-2 rounded-full" style={{ background: 'var(--gold-primary)' }} />
            <h2 className="font-display text-base" style={{ color: 'var(--text-primary)' }}>IPFS Document Registry</h2>
            <span className="px-2 py-0.5 rounded text-[9px] font-body uppercase tracking-wider" style={{ background: 'rgba(212,175,55,0.12)', color: 'var(--gold-primary)', border: '1px solid rgba(212,175,55,0.3)' }}>
              10 / 10 Pinned
            </span>
          </div>
          <span className="text-[10px] font-body" style={{ color: 'var(--text-ghost)' }}>Pinned via Pinata · Arbitrum Sepolia</span>
        </div>

        <div className="px-6 py-5 space-y-5">
          <p className="text-sm font-body leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
            All legal documents are pinned to IPFS via Pinata and accessible via <code className="font-data text-xs" style={{ color: 'var(--gold-primary)' }}>ipfs.io</code> and <code className="font-data text-xs" style={{ color: 'var(--gold-primary)' }}>gateway.pinata.cloud</code> gateways.
            CIDs are immutable — content is guaranteed identical across all gateways.
          </p>

          {[
            {
              property: 'The Pearl Residences', ticker: 'PEARL-DXB-001',
              docs: [
                { name: 'SPV Structure Document',    cid: 'QmaVooqBwZjjkCQAvfodgtpGvfmifqQQgyPkj45m3AXMfu' },
                { name: 'Property Valuation Report', cid: 'Qmep6ua83jnqGEYgFvEzFt7xuXntP7mCDhSGy9VqH4m92w' },
                { name: 'Rental Agreement',          cid: 'QmcNvbSwHecj9sxHZvz9GaJwCZcWnCLbALCes653kBY7KZ' },
              ],
            },
            {
              property: 'Shibuya Terrace', ticker: 'SHIBUYA-TYO-001',
              docs: [
                { name: 'SPV Structure Document',    cid: 'QmdCLkDwBq9KcGBmDB1NGsGxEtJd5KqgsW2vAMhR1qaXqT' },
                { name: 'Property Valuation Report', cid: 'QmQoKfhdfUfuWwTKcpZ3eeiMSqsasntftSSbkMzA32h1sU' },
              ],
            },
            {
              property: 'Marina Heights', ticker: 'MARINA-SGP-001',
              docs: [
                { name: 'SPV Structure Document', cid: 'QmPzTpiTzYcQNJ12eGRjvYtXVj6vHtcHK2UtJZpfD3wtAJ' },
              ],
            },
            {
              property: 'Canary Wharf Executive', ticker: 'CANARY-LON-001',
              docs: [
                { name: 'SPV Structure Document',    cid: 'QmZf53DUoSH5wGJKeLPrLq4SFbaKj2nncWNa5TnJ9rjAVu' },
                { name: 'Property Valuation Report', cid: 'QmQTNv8wSxmtAhnUZwb2jtVHKWVhW9x8u1nmdZ2d5pzuek' },
                { name: 'Lease Agreement',           cid: 'QmaMgjXMqUvTbwMLicL2TcAbhR6mxHuz4JEeoXoA3MYnfF' },
              ],
            },
            {
              property: 'Azure Barcelona Suite', ticker: 'AZURE-BCN-001',
              docs: [
                { name: 'SPV Structure Document', cid: 'QmUe6PK91ZHbPGtwE6tqyp1K2AX2NYboLvzBy9usd99oxq' },
              ],
            },
          ].map(p => (
            <div key={p.ticker}>
              <div className="flex items-center gap-2 mb-2">
                <span className="text-[10px] font-data" style={{ color: 'var(--gold-primary)' }}>{p.ticker}</span>
                <span className="text-[10px] font-body" style={{ color: 'var(--text-ghost)' }}>— {p.property}</span>
              </div>
              <div className="rounded-xl overflow-hidden" style={{ border: '1px solid var(--border-subtle)' }}>
                {p.docs.map((doc, i) => (
                  <div
                    key={doc.cid}
                    className="grid grid-cols-[1fr_auto] items-center px-4 py-3 gap-4"
                    style={{ borderTop: i > 0 ? '1px solid var(--border-subtle)' : 'none', background: i % 2 === 0 ? 'transparent' : 'rgba(255,255,255,0.01)' }}
                  >
                    <div>
                      <p className="text-xs font-body mb-0.5" style={{ color: 'var(--text-secondary)' }}>{doc.name}</p>
                      <code className="text-[10px] font-data break-all" style={{ color: 'var(--text-ghost)' }}>{doc.cid}</code>
                    </div>
                    <div className="flex items-center gap-3 shrink-0">
                      <span
                        className="flex items-center gap-1 px-2 py-0.5 rounded-full text-[9px] font-body uppercase tracking-widest"
                        style={{ background: 'rgba(0,229,160,0.08)', border: '1px solid rgba(0,229,160,0.2)', color: 'var(--nox-green)' }}
                      >
                        <span className="h-1 w-1 rounded-full" style={{ background: 'var(--nox-green)' }} />
                        Pinned
                      </span>
                      <a
                        href={`https://ipfs.io/ipfs/${doc.cid}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-[10px] font-body transition-opacity hover:opacity-70"
                        style={{ color: 'var(--gold-primary)' }}
                      >
                        ↗ IPFS
                      </a>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Contract cards */}
      <div className="space-y-8">
        {CONTRACTS.map(c => (
          <div key={c.name} className="rounded-xl overflow-hidden" style={{ border: '1px solid var(--border-visible)' }}>
            {/* Header */}
            <div className="flex flex-wrap items-center justify-between gap-3 px-6 py-4" style={{ background: 'var(--bg-elevated)', borderBottom: '1px solid var(--border-subtle)' }}>
              <div className="flex items-center gap-3">
                <span
                  className="px-2 py-0.5 rounded text-[9px] font-body uppercase tracking-wider"
                  style={{ background: 'rgba(0,0,0,0.3)', color: c.badgeColor, border: `1px solid ${c.badgeColor}40` }}
                >
                  {c.badge}
                </span>
                <h2 className="font-data text-base" style={{ color: 'var(--text-primary)' }}>{c.name}</h2>
              </div>
              <a
                href={`https://sepolia.arbiscan.io/address/${c.address}`}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[10px] font-data transition-opacity hover:opacity-70"
                style={{ color: 'var(--text-ghost)' }}
              >
                {c.address.slice(0, 10)}…{c.address.slice(-6)} ↗
              </a>
            </div>

            <div className="px-6 py-5">
              <p className="text-sm font-body leading-relaxed mb-4" style={{ color: 'var(--text-secondary)' }}>{c.desc}</p>

              <div className="mb-4">
                <p className="text-[10px] font-body uppercase tracking-widest mb-2" style={{ color: 'var(--text-ghost)' }}>Inherits</p>
                <div className="flex flex-wrap gap-2">
                  {c.inherits.map(i => (
                    <span key={i} className="px-2 py-0.5 rounded text-[10px] font-data" style={{ background: 'var(--bg-elevated)', color: 'var(--text-secondary)', border: '1px solid var(--border-subtle)' }}>
                      {i}
                    </span>
                  ))}
                </div>
              </div>

              <div className="mb-4">
                <p className="text-[10px] font-body uppercase tracking-widest mb-2" style={{ color: 'var(--text-ghost)' }}>Key Functions</p>
                <div className="space-y-2">
                  {c.functions.map(fn => (
                    <div key={fn.sig} className="rounded-lg p-3" style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border-subtle)' }}>
                      <div className="flex flex-wrap items-start gap-2 mb-1">
                        <code className="text-[11px] font-data leading-relaxed" style={{ color: c.badgeColor }}>{fn.sig}</code>
                        <span className="shrink-0 px-1.5 py-0.5 rounded text-[9px] font-body uppercase" style={{ background: 'rgba(0,0,0,0.3)', color: 'var(--text-ghost)', border: '1px solid var(--border-subtle)' }}>
                          {fn.access}
                        </span>
                      </div>
                      <p className="text-xs font-body" style={{ color: 'var(--text-ghost)' }}>{fn.desc}</p>
                    </div>
                  ))}
                </div>
              </div>

              {c.notes.length > 0 && (
                <div>
                  <p className="text-[10px] font-body uppercase tracking-widest mb-2" style={{ color: 'var(--text-ghost)' }}>Notes</p>
                  <ul className="space-y-1">
                    {c.notes.map(n => (
                      <li key={n} className="flex items-start gap-2 text-xs font-body" style={{ color: 'var(--text-ghost)' }}>
                        <span style={{ color: c.badgeColor }}>·</span>{n}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
