const CONTRACTS = [
  {
    name: 'PropertyToken.sol',
    badge: 'ERC-7984',
    badgeColor: 'var(--nox-green)',
    address: '0x853D51fBD5E288BF189FE0126d59f855c821a641',
    addressLabel: 'PEARL-DXB-001 (example)',
    desc: 'One instance per property, deployed via CREATE2 from PropertyRegistry. The core confidential token — balances stored as euint256, encrypted by Intel TDX TEE. No observer can read holdings.',
    inherits: ['ERC7984 (iExec Nox)', 'Ownable', 'Pausable', 'ReentrancyGuard'],
    functions: [
      { sig: 'purchaseTokens(bytes32 handle, bytes handleProof, uint256 clearAmount)', access: 'public', desc: 'Pay USDT, receive encrypted tokens. handle + handleProof generated by @iexec-nox/handle SDK.' },
      { sig: 'grantOperator(address operator, uint256 expiry)', access: 'holder', desc: 'Delegate transfer rights to SecondaryMarket for listings. Expiry in unix timestamp.' },
      { sig: 'pricePerToken() → uint256', access: 'view', desc: 'Token price in USDT 6 decimals. All 5 deployed = 1_000_000 ($1.00).' },
      { sig: 'propertyId() → uint256', access: 'view', desc: 'ID assigned by PropertyRegistry (1–5 for current properties).' },
    ],
    notes: [
      'Transfers never revert on insufficient balance (ERC-7984 spec — prevents balance inference via gas)',
      'Events do not emit token amounts — privacy by design',
      'Salt for CREATE2 = bytes32(propertyId) → deterministic addresses',
    ],
  },
  {
    name: 'PropertyRegistry.sol',
    badge: 'Factory',
    badgeColor: 'var(--gold-primary)',
    address: '0xCdBCA38E4C86bdC74Cd49D93cE2B88D3ecC00d5e',
    addressLabel: 'Registry (all networks)',
    desc: 'Central registry and CREATE2 factory. Admin lists properties, which deploys a new PropertyToken. Tracks all holders per property for RentDistributor. Currently 5 active properties.',
    inherits: ['Ownable', 'Pausable', 'ReentrancyGuard'],
    functions: [
      { sig: 'listProperty(string name, string location, string ipfsDocHash, uint256 totalSupply, uint256 pricePerToken, uint256 monthlyRent) → (uint256 propertyId, address tokenContract)', access: 'onlyOwner', desc: 'Deploys PropertyToken via CREATE2, registers property. pricePerToken in USDT 6 decimals.' },
      { sig: 'registerHolder(uint256 propertyId, address holder)', access: 'approved', desc: 'Called by PropertyToken on purchase and by approved markets. Prevents duplicate entries.' },
      { sig: 'setApprovedMarket(address market, bool approved)', access: 'onlyOwner', desc: 'Whitelist SecondaryMarket to register buyers as holders post-trade.' },
      { sig: 'getPropertyHolders(uint256 propertyId) → address[]', access: 'view', desc: 'Returns all registered holder addresses. Used by RentDistributor.' },
      { sig: 'properties(uint256) → Property', access: 'view', desc: 'Returns full property struct: id, name, location, supply, price, rent, status, tokenContract.' },
      { sig: 'propertyCount() → uint256', access: 'view', desc: 'Total properties listed. Currently 5.' },
    ],
    notes: [
      'owner() = 0x834De729cb9dF77451DBc6bf7FD05F475B011Ac7 (treasury/deployer)',
      'paused() = false (all contracts operational)',
    ],
  },
  {
    name: 'SecondaryMarket.sol',
    badge: 'P2P Marketplace',
    badgeColor: 'var(--gold-primary)',
    address: '0x77836405DC14Ca1Ef0304041ec8D3B4166424cfa',
    addressLabel: 'Secondary Market',
    desc: 'Fixed-price P2P listing marketplace for property token trading. Sellers post a listing at a fixed price; buyers execute against it. Token amounts moved via confidentialTransferFrom (encrypted). CEST stakers get fee discounts.',
    inherits: ['ReentrancyGuard', 'Pausable'],
    functions: [
      { sig: 'createListing(address tokenContract, uint256 propertyId, uint256 tokenAmount, uint256 pricePerToken) → uint256 listingId', access: 'public', desc: 'Requires grantOperator first. pricePerToken in USDT 6 decimals (e.g. $1.025 = 1_025_000). Returns listingId.' },
      { sig: 'executeBuy(uint256 listingId)', access: 'public', desc: 'Buyer must approve USDT first. Triggers confidentialTransferFrom (encrypted). Deducts 0.5% fee (reduced by CEST tier).' },
      { sig: 'cancelListing(uint256 listingId)', access: 'seller', desc: 'Seller can cancel an active listing at any time.' },
      { sig: 'listings(uint256) → Listing', access: 'view', desc: 'Returns: listingId, seller, tokenContract, propertyId, tokenAmount, pricePerToken, listedAt, active.' },
    ],
    notes: [
      'Fee: 0.5% base, reduced by CEST staking tier (0% for PLATINUM)',
      'Seller must call propertyToken.grantOperator(secondaryMarket, expiry) before listing',
      'Buyer must call usdt.approve(secondaryMarket, totalCost) before executeBuy',
    ],
  },
  {
    name: 'RentDistributor.sol',
    badge: 'Income',
    badgeColor: 'var(--nox-green)',
    address: '0x80E0e5f6488FA2726c042a204344281974f72609',
    addressLabel: 'Rent Distributor',
    desc: 'Receives monthly USDT from the property operator and distributes 90% to all registered holders. Platform takes 5%, maintenance reserve 5%. Equal-share model (not pro-rata) because ERC-7984 balances cannot be read on-chain.',
    inherits: ['ReentrancyGuard', 'Pausable', 'Ownable'],
    functions: [
      { sig: 'depositRent(uint256 propertyId, uint256 amount)', access: 'onlyOwner', desc: 'Deposit USDT rent for a property. Accumulates in pendingRent[propertyId].' },
      { sig: 'distributeRent(uint256 propertyId)', access: 'onlyOwner', desc: 'Distribute accumulated pendingRent — splits: 5% platform + 5% maintenance + 90% equally to all holders.' },
      { sig: 'getDistributionHistory(uint256 propertyId) → RentDistribution[]', access: 'view', desc: 'Returns past distributions for a property.' },
      { sig: 'getPendingRent(uint256 propertyId) → uint256', access: 'view', desc: 'Returns accumulated undistributed rent for a property.' },
    ],
    notes: [
      'Equal share per holder — not pro-rata by token balance',
      'Pro-rata distribution planned for Phase 2 using iExec Nox compute over encrypted balances',
      'All distribution totals are on-chain auditable; per-investor amounts are private',
    ],
  },
  {
    name: 'CESTToken.sol',
    badge: 'ERC20Votes',
    badgeColor: 'var(--gold-primary)',
    address: '0xC6c08db835636Cf40530dDf90Bf3Bb15bc78190D',
    addressLabel: 'CEST Token',
    desc: 'Utility and future-governance token. 1 Billion total supply. Current utility: time-lock staking for SecondaryMarket fee discounts (0.5% → 0% at PLATINUM). ERC20Votes is inherited for Compound-style delegation — it enables future DAO governance but is NOT used by ConfidentialGovernance.sol (which uses PropertyToken holder status instead). Price: $0.04 → $40M market cap.',
    inherits: ['ERC20', 'ERC20Votes', 'ERC20Permit', 'Ownable'],
    functions: [
      { sig: 'stake(uint256 amount, uint256 lockDays)', access: 'public', desc: 'Time-lock CEST for fee discount tier. Min 30 days, max 365 days. Adds to existing staked amount.' },
      { sig: 'unstake(uint256 amount)', access: 'holder', desc: 'Withdraw a specific amount of staked CEST after lock period expires. Tier recalculates automatically.' },
      { sig: 'getTier(address account) → Tier', access: 'view', desc: 'Returns NONE/BRONZE/SILVER/GOLD/PLATINUM based on staked balance.' },
      { sig: 'getFeeDiscount(address account) → uint256', access: 'view', desc: 'Returns discount in BPS (0–10000). PLATINUM = 10000 (100% free). Used by SecondaryMarket.' },
    ],
    notes: [
      'ERC20Votes = delegation only (future DAO) — ConfidentialGovernance uses PropertyToken holder status, not CEST',
      'Faucet drips 2,400 CEST (~$96) per address per 24h on testnet',
      'Total supply: 1,000,000,000 · Airdrop pool: 250,000,000 (25%)',
      'Uniswap listing planned Q2 2026 — not yet live on any DEX',
    ],
  },
  {
    name: 'ConfidentialGovernance.sol',
    badge: 'Governance',
    badgeColor: 'var(--nox-green)',
    address: '0x32AC35493ff1E4a550C36AB6BfD2f29a2b021a14',
    addressLabel: 'Confidential Governance',
    desc: 'Property-level governance gated by PropertyToken (ERC-7984) holder status — NOT by CEST token. Each verified holder gets exactly 1 vote regardless of their encrypted token balance, preventing whale dominance while preserving full privacy. Holder status checked via registry.isHolder().',
    inherits: ['Ownable'],
    functions: [
      { sig: 'createProposal(uint256 propertyId, ProposalType proposalType, string description) → uint256 proposalId', access: 'onlyHolder', desc: 'Create a governance proposal for a property. ProposalType: RentAdjustment | Maintenance | PropertyStatus | Other.' },
      { sig: 'castVote(uint256 proposalId, VoteOption option)', access: 'holder', desc: '1 address = 1 vote. VoteOption: For | Against | Abstain. Balance-blind — no whale advantage visible on-chain.' },
      { sig: 'finalizeProposal(uint256 proposalId)', access: 'public', desc: 'Finalize a proposal after voting deadline. Checks quorum and majority. Any address can call.' },
      { sig: 'getProposal(uint256 proposalId) → Proposal', access: 'view', desc: 'Returns full proposal struct including vote counts and execution status.' },
      { sig: 'getProposalsByProperty(uint256 propertyId) → Proposal[]', access: 'view', desc: 'Returns all proposals for a property.' },
    ],
    notes: [
      'Access control: registry.isHolder(propertyId, msg.sender) — no balance exposed',
      '1 address = 1 vote (balance-blind for privacy)',
      'Proposals: rent adjustments, maintenance, property status changes',
    ],
  },
]

export default function ContractsPage() {
  return (
    <div>
      <p className="text-xs font-body uppercase tracking-[0.28em] mb-3" style={{ color: 'var(--nox-green)' }}>
        Docs / Smart Contracts
      </p>
      <h1 className="font-display text-4xl mb-4" style={{ color: 'var(--text-primary)' }}>
        Smart Contracts
      </h1>
      <p className="text-base font-body leading-relaxed mb-4 max-w-2xl" style={{ color: 'var(--text-secondary)' }}>
        All contracts are deployed and verified on Arbitrum Sepolia (chainId 421614).
        Source in <code className="font-data text-sm" style={{ color: 'var(--gold-primary)' }}>contracts/</code>.
        ABIs in <code className="font-data text-sm" style={{ color: 'var(--gold-primary)' }}>artifacts/</code>.
        Frontend ABIs in <code className="font-data text-sm" style={{ color: 'var(--gold-primary)' }}>app/lib/contracts.ts</code>.
      </p>

      {/* Architecture diagram */}
      <div className="rounded-xl p-5 mb-10 font-data text-xs leading-relaxed" style={{ background: 'var(--bg-surface)', border: '1px solid var(--border-visible)', color: 'var(--text-secondary)' }}>
        <p className="mb-1" style={{ color: 'var(--text-ghost)' }}>// Architecture</p>
        <pre className="overflow-x-auto">{`Wallet
  │
  ├─ @iexec-nox/handle → { handle, handleProof }
  │
  ├─ usdt.approve(PropertyToken, amount)
  └─ PropertyToken.purchaseTokens(handle, proof, amount)
         │  euint256 balance (encrypted in ERC-7984)
         │
         ├─ PropertyRegistry.registerHolder(propertyId, wallet)
         │        │
         │        └─ RentDistributor.distributeRent() → USDT per holder
         │
         └─ SecondaryMarket
                  │  grantOperator → createListing(tokenContract, id, amount, price)
                  │  usdt.approve(SecondaryMarket) → executeBuy(listingId)
                  │  confidentialTransferFrom (encrypted)
                  │
                  └─ ConfidentialGovernance
                           │  registry.isHolder() → onlyHolder
                           └─ createProposal / vote / executeProposal`}</pre>
      </div>

      {/* iApp Live Test Evidence */}
      <div className="rounded-xl overflow-hidden mb-10" style={{ border: '1px solid rgba(0,229,160,0.3)' }}>
        <div className="flex flex-wrap items-center justify-between gap-3 px-6 py-4" style={{ background: 'rgba(0,229,160,0.07)', borderBottom: '1px solid rgba(0,229,160,0.2)' }}>
          <div className="flex items-center gap-3">
            <span className="h-2 w-2 rounded-full" style={{ background: 'var(--nox-green)', boxShadow: '0 0 8px rgba(0,229,160,0.6)' }} />
            <h2 className="font-display text-base" style={{ color: 'var(--text-primary)' }}>iApp Live Test Evidence</h2>
            <span className="px-2 py-0.5 rounded text-[9px] font-body uppercase tracking-wider" style={{ background: 'rgba(0,229,160,0.12)', color: 'var(--nox-green)', border: '1px solid rgba(0,229,160,0.3)' }}>
              Verified on iExec
            </span>
          </div>
          <a
            href="https://explorer.iex.ec/bellecour/address/0x834De729cb9dF77451DBc6bf7FD05F475B011Ac7"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[10px] font-data transition-opacity hover:opacity-70"
            style={{ color: 'var(--text-ghost)' }}
          >
            View on iExec Explorer ↗
          </a>
        </div>

        <div className="px-6 py-5 space-y-6">
          <p className="text-sm font-body leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
            The iExec Nox iApp was live-tested on <strong style={{ color: 'var(--text-primary)' }}>April 30, 2026</strong> against the Arbitrum Sepolia PropertyToken contracts.
            4 of 5 tasks completed successfully (1 timeout — expected on testnet). All deals used the same Intel TDX enclave, confirming the full TEE encryption pipeline is operational end-to-end.
          </p>

          {/* Stats row */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {[
              { label: 'Tasks Completed', value: '4 / 5', color: 'var(--nox-green)' },
              { label: 'Success Rate', value: '80%', color: 'var(--nox-green)', sub: '(4 of 5, 1 timeout)' },
              { label: 'Deal Price', value: '0.1 RLC', color: 'var(--gold-primary)' },
              { label: 'Test Date', value: '30 Apr 2026', color: 'var(--text-secondary)' },
            ].map(s => (
              <div key={s.label} className="rounded-xl p-3 text-center" style={{ background: 'rgba(0,0,0,0.3)', border: '1px solid var(--border-subtle)' }}>
                <p className="text-[10px] font-body uppercase tracking-widest mb-1" style={{ color: 'var(--text-ghost)' }}>{s.label}</p>
                <p className="font-data text-lg" style={{ color: s.color }}>{s.value}</p>
                {s.sub && <p className="text-[9px] font-body mt-0.5" style={{ color: 'var(--text-ghost)' }}>{s.sub}</p>}
              </div>
            ))}
          </div>

          {/* iApp + Workerpool */}
          <div className="grid gap-3 sm:grid-cols-2">
            <div className="rounded-xl p-4" style={{ background: 'rgba(0,229,160,0.04)', border: '1px solid rgba(0,229,160,0.15)' }}>
              <p className="text-[10px] font-body uppercase tracking-widest mb-2" style={{ color: 'var(--text-ghost)' }}>iApp (TEE Enclave)</p>
              <a
                href="https://explorer.iex.ec/bellecour/app/0xB11bC7288eE239F6536829E410d22Eb514C5E282"
                target="_blank"
                rel="noopener noreferrer"
                className="font-data text-xs hover:opacity-70 transition-opacity"
                style={{ color: 'var(--nox-green)' }}
              >
                0xB11bC7288eE239F6536829E410d22Eb514C5E282 ↗
              </a>
              <p className="text-[10px] font-body mt-2" style={{ color: 'var(--text-ghost)' }}>jancok075/iexec:0.0.1-tdx-1f1d5e8f915a</p>
              <p className="text-[10px] font-body mt-0.5" style={{ color: 'var(--text-ghost)' }}>Tag: tee,tdx — Intel TDX hardware enclave</p>
            </div>
            <div className="rounded-xl p-4" style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid var(--border-subtle)' }}>
              <p className="text-[10px] font-body uppercase tracking-widest mb-2" style={{ color: 'var(--text-ghost)' }}>Workerpool</p>
              <p className="font-data text-xs" style={{ color: 'var(--gold-primary)' }}>0x2956f0...3123f</p>
              <p className="text-[10px] font-body mt-2" style={{ color: 'var(--text-ghost)' }}>Requester wallet</p>
              <a
                href="https://explorer.iex.ec/bellecour/address/0x834De729cb9dF77451DBc6bf7FD05F475B011Ac7"
                target="_blank"
                rel="noopener noreferrer"
                className="font-data text-[10px] hover:opacity-70 transition-opacity"
                style={{ color: 'var(--text-ghost)' }}
              >
                0x834De7…011Ac7 ↗
              </a>
            </div>
          </div>

          {/* Task log */}
          <div>
            <p className="text-[10px] font-body uppercase tracking-widest mb-3" style={{ color: 'var(--text-ghost)' }}>Completed Task Log — April 30, 2026</p>
            <div className="rounded-xl overflow-hidden" style={{ border: '1px solid var(--border-subtle)' }}>
              <div className="grid grid-cols-[1fr_120px_1fr] px-4 py-2 text-[10px] font-body uppercase tracking-widest" style={{ background: 'var(--bg-elevated)', color: 'var(--text-ghost)', borderBottom: '1px solid var(--border-subtle)' }}>
                <span>Task ID</span><span>Status</span><span>Deadline</span>
              </div>
              {[
                { id: '0x423c62…8a4d9', status: 'COMPLETED', time: '04/30/2026 11:26 AM', ok: true },
                { id: '0x6091cf…5df0d', status: 'COMPLETED', time: '04/30/2026 09:42 AM', ok: true },
                { id: '0x5b434e…dfdea', status: 'COMPLETED', time: '04/30/2026 09:40 AM', ok: true },
                { id: '0x6268ea…0982b', status: 'COMPLETED', time: '04/30/2026 09:38 AM', ok: true },
                { id: '0xb5a7f1…9335b', status: 'TIMEOUT',   time: '04/30/2026 09:31 AM', ok: false },
              ].map((t, i, arr) => (
                <div
                  key={t.id}
                  className="grid grid-cols-[1fr_120px_1fr] px-4 py-3 text-xs font-body items-center"
                  style={{ borderTop: i > 0 ? '1px solid var(--border-subtle)' : 'none', background: i % 2 === 0 ? 'transparent' : 'rgba(255,255,255,0.01)' }}
                >
                  <code className="font-data text-[11px]" style={{ color: 'var(--text-secondary)' }}>{t.id}</code>
                  <span
                    className="inline-flex items-center gap-1.5 text-[10px] uppercase tracking-widest"
                    style={{ color: t.ok ? 'var(--nox-green)' : 'var(--text-ghost)' }}
                  >
                    <span className="h-1.5 w-1.5 rounded-full shrink-0" style={{ background: t.ok ? 'var(--nox-green)' : 'var(--text-ghost)' }} />
                    {t.status}
                  </span>
                  <span className="font-data text-[10px]" style={{ color: 'var(--text-ghost)' }}>{t.time}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Deal log */}
          <div>
            <p className="text-[10px] font-body uppercase tracking-widest mb-3" style={{ color: 'var(--text-ghost)' }}>Deal Log — All using iApp 0xb11bc7…5e282</p>
            <div className="rounded-xl overflow-hidden" style={{ border: '1px solid var(--border-subtle)' }}>
              <div className="grid grid-cols-[1fr_80px_60px_60px] px-4 py-2 text-[10px] font-body uppercase tracking-widest" style={{ background: 'var(--bg-elevated)', color: 'var(--text-ghost)', borderBottom: '1px solid var(--border-subtle)' }}>
                <span>Deal ID</span><span>Time</span><span>Success</span><span>Price</span>
              </div>
              {[
                { id: '0x8e424d…9119c', time: '2h ago', success: '100%', ok: true },
                { id: '0x31da2e…17358', time: '4h ago', success: '100%', ok: true },
                { id: '0xfd1df0…95206', time: '4h ago', success: '100%', ok: true },
                { id: '0x491b08…34b5e', time: '4h ago', success: '100%', ok: true },
                { id: '0x88d811…d129a', time: '4h ago', success: '0%',   ok: false },
              ].map((d, i) => (
                <div
                  key={d.id}
                  className="grid grid-cols-[1fr_80px_60px_60px] px-4 py-3 text-xs font-body items-center"
                  style={{ borderTop: i > 0 ? '1px solid var(--border-subtle)' : 'none', background: i % 2 === 0 ? 'transparent' : 'rgba(255,255,255,0.01)' }}
                >
                  <code className="font-data text-[11px]" style={{ color: 'var(--text-secondary)' }}>{d.id}</code>
                  <span className="font-data text-[10px]" style={{ color: 'var(--text-ghost)' }}>{d.time}</span>
                  <span className="font-data text-[11px]" style={{ color: d.ok ? 'var(--nox-green)' : 'var(--text-ghost)' }}>{d.success}</span>
                  <span className="font-data text-[10px]" style={{ color: 'var(--gold-primary)' }}>0.1 RLC</span>
                </div>
              ))}
            </div>
            <p className="mt-2 text-[10px] font-body" style={{ color: 'var(--text-ghost)' }}>
              1 timeout (0%) is expected on Bellecour testnet — task started but workerpool was unavailable. No RLC deducted.
            </p>
          </div>
        </div>
      </div>

      {/* Contract cards */}
      <div className="space-y-8">
        {CONTRACTS.map(c => (
          <div key={c.name} className="rounded-xl overflow-hidden" style={{ border: '1px solid var(--border-visible)' }}>
            {/* Header */}
            <div className="flex flex-wrap items-center justify-between gap-3 px-6 py-4" style={{ background: 'var(--bg-elevated)', borderBottom: '1px solid var(--border-subtle)' }}>
              <div className="flex items-center gap-3">
                <span
                  className="px-2 py-0.5 rounded text-[9px] font-body uppercase tracking-wider"
                  style={{ background: 'rgba(0,0,0,0.3)', color: c.badgeColor, border: `1px solid ${c.badgeColor}40` }}
                >
                  {c.badge}
                </span>
                <h2 className="font-data text-base" style={{ color: 'var(--text-primary)' }}>{c.name}</h2>
              </div>
              <a
                href={`https://sepolia.arbiscan.io/address/${c.address}`}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[10px] font-data transition-opacity hover:opacity-70"
                style={{ color: 'var(--text-ghost)' }}
              >
                {c.address.slice(0, 10)}…{c.address.slice(-6)} ↗
              </a>
            </div>

            <div className="px-6 py-5">
              <p className="text-sm font-body leading-relaxed mb-4" style={{ color: 'var(--text-secondary)' }}>{c.desc}</p>

              <div className="mb-4">
                <p className="text-[10px] font-body uppercase tracking-widest mb-2" style={{ color: 'var(--text-ghost)' }}>Inherits</p>
                <div className="flex flex-wrap gap-2">
                  {c.inherits.map(i => (
                    <span key={i} className="px-2 py-0.5 rounded text-[10px] font-data" style={{ background: 'var(--bg-elevated)', color: 'var(--text-secondary)', border: '1px solid var(--border-subtle)' }}>
                      {i}
                    </span>
                  ))}
                </div>
              </div>

              <div className="mb-4">
                <p className="text-[10px] font-body uppercase tracking-widest mb-2" style={{ color: 'var(--text-ghost)' }}>Key Functions</p>
                <div className="space-y-2">
                  {c.functions.map(fn => (
                    <div key={fn.sig} className="rounded-lg p-3" style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border-subtle)' }}>
                      <div className="flex flex-wrap items-start gap-2 mb-1">
                        <code className="text-[11px] font-data leading-relaxed" style={{ color: c.badgeColor }}>{fn.sig}</code>
                        <span className="shrink-0 px-1.5 py-0.5 rounded text-[9px] font-body uppercase" style={{ background: 'rgba(0,0,0,0.3)', color: 'var(--text-ghost)', border: '1px solid var(--border-subtle)' }}>
                          {fn.access}
                        </span>
                      </div>
                      <p className="text-xs font-body" style={{ color: 'var(--text-ghost)' }}>{fn.desc}</p>
                    </div>
                  ))}
                </div>
              </div>

              {c.notes.length > 0 && (
                <div>
                  <p className="text-[10px] font-body uppercase tracking-widest mb-2" style={{ color: 'var(--text-ghost)' }}>Notes</p>
                  <ul className="space-y-1">
                    {c.notes.map(n => (
                      <li key={n} className="flex items-start gap-2 text-xs font-body" style={{ color: 'var(--text-ghost)' }}>
                        <span style={{ color: c.badgeColor }}>·</span>{n}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
